-- Archive table for discharged cases, written by RecordArchiveWorker.
--
-- Mirrors PatientCaseEntity exactly: Hibernate runs in `validate` mode, so any drift between
-- this file and the entity fails the application at startup rather than silently at runtime.
-- treatment_plan and discharge_summary are TEXT because clinical narratives are unbounded;
-- the remaining string columns use Hibernate's default length.
--
-- The unique constraint on case_id is what makes archiving safe under concurrent retries —
-- the framework's idempotency guard covers the common case, this covers the race.

CREATE TABLE patient_case (
    id                BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    case_id           VARCHAR(255) NOT NULL UNIQUE,
    patient_id        VARCHAR(255),
    patient_name      VARCHAR(255),
    care_plan         VARCHAR(255),
    treatment_plan    TEXT,
    discharge_summary TEXT,
    vitals_trend      VARCHAR(255),
    archived_at       TIMESTAMP
);
