-- Audit trail of human steps completed through this service's task API.
--
-- Camunda records that a task completed, but its history is retention-bound and carries no notion
-- of who acted in this service's terms. This table outlives the engine's history and is what
-- GET /api/v1/cases/{key}/tasks/outcomes reads.
--
-- Mirrors CaseTaskOutcomeEntity exactly: Hibernate runs in `validate` mode, so any drift between
-- this file and the entity fails the application at startup rather than silently at runtime.
--
-- No unique constraint: completing the same element twice is legitimate here. The revise-plan loop
-- walks Task_TreatmentPlan and Task_TreatmentAdmin once per pass, and each pass is a distinct
-- clinical act that the audit trail should show separately.

CREATE TABLE case_task_outcome (
    id                   BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    case_id              VARCHAR(255),
    process_instance_key BIGINT       NOT NULL,
    user_task_key        BIGINT       NOT NULL,
    element_id           VARCHAR(255),
    task_name            VARCHAR(255),
    completed_by         VARCHAR(255),
    variables            TEXT,
    created_at           TIMESTAMP    NOT NULL
);

-- Every read is "the trail for one journey", so the instance key is the only index worth having.
CREATE INDEX idx_case_task_outcome_pik ON case_task_outcome (process_instance_key);
